using System.Text.Json.Nodes;
using DotnetToolkit.McpServer.Telemetry;

namespace DotnetToolkit.McpServer.Hooks;

/// <summary>
/// <c>PostToolUse</c> hook on every tool: reports what one tool call cost, in both directions, to the
/// running server over the loopback control channel.
/// </summary>
/// <remarks>
/// This exists because the server cannot measure the thing it is being compared against. Its own
/// <c>retrieval_events</c> rows are written from inside a tool method, so they cover MCP tools and
/// nothing else — a <c>Grep</c> or a <c>Read</c> never reaches this process, and a benchmark that meters
/// one route with the server and the other by asking an agent to count its own calls is not a
/// comparison. A <c>PostToolUse</c> hook fires on harness dispatch, independent of which tools an
/// agent's grant contains, so both routes are measured by the same code on the same payload.
/// <para>
/// The two directions are priced differently and are kept apart for that reason: <c>tool_response</c>
/// is loaded into the model's context (input tokens, the cheap side), while <c>tool_input</c> had to be
/// generated by the model (output tokens, several times dearer). Counting is done here rather than
/// server-side so the wire carries two integers instead of a whole tool response, and it uses
/// <see cref="TelemetryRecorder.EstimateTokens"/> — the same function the server's own telemetry uses,
/// which is what makes the two tables comparable at all.
/// </para>
/// <para>
/// <b>Fails open and silently.</b> A measurement hook must never interrupt the work it is measuring, so
/// an unreachable server, a payload with no <c>tool_use_id</c>, or any other surprise simply records
/// nothing. The tell is a call count below the transcript's own <c>tool_uses</c>, which is a comparison
/// the perf report already makes.
/// </para>
/// </remarks>
internal static class ToolCallMeter
{
    /// <summary>Names the approximation behind the counts, so a later recalibration is distinguishable.</summary>
    public const string Estimator = "chars4";

    /// <summary>Meters one completed tool call and reports it to the running server.</summary>
    /// <param name="payload">The parsed hook payload, carrying both directions of the call.</param>
    /// <param name="context">The repo root whose control channel to report to.</param>
    /// <returns>Always an allow outcome: this hook observes, and never withholds a call.</returns>
    public static async Task<HookOutcome> EvaluateAsync(HookPayload payload, HookContext context)
    {
        // Without the harness's own id there is no way to tell a redelivery from a second call, and the
        // table's UNIQUE constraint is what makes this idempotent. Better to record nothing than to
        // record something that cannot be reconciled against the transcript.
        if (string.IsNullOrEmpty(payload.ToolUseId))
        {
            return HookOutcome.Allow;
        }

        var measurement = new JsonObject
        {
            ["toolName"] = payload.ToolName,
            ["toolUseId"] = payload.ToolUseId,
            ["requestTokens"] = TelemetryRecorder.EstimateTokens(payload.ToolInputRaw),
            ["responseTokens"] = TelemetryRecorder.EstimateTokens(payload.ToolResponseRaw),
            ["estimator"] = Estimator,
            ["claudeSessionId"] = payload.SessionId,
            ["guardSessionId"] = GuardSuspension.CurrentSessionId(),
            ["agentId"] = payload.AgentId,
            ["agentType"] = payload.AgentType,
        };

        await ControlClient.SendAsync(
            context.Root,
            Control.ControlCommands.Meter + " " + measurement.ToJsonString());

        return HookOutcome.Allow;
    }
}
